const countryData = [
    { name: "Afghanistan", flag: "AF", currency: "AFN" },
    { name: "Albania", flag: "AL", currency: "ALL" },
    { name: "Algeria", flag: "DZ", currency: "DZD" },
    { name: "Andorra", flag: "AD", currency: "EUR" },
    { name: "Angola", flag: "AO", currency: "AOA" },
    { name: "Antigua and Barbuda", flag: "AG", currency: "XCD" },
    { name: "Argentina", flag: "AR", currency: "ARS" },
    { name: "Armenia", flag: "AM", currency: "AMD" },
    { name: "Australia", flag: "AU", currency: "AUD" },
    { name: "Austria", flag: "AT", currency: "EUR" },
    { name: "Azerbaijan", flag: "AZ", currency: "AZN" },
    { name: "Bahamas", flag: "BS", currency: "BSD" },
    { name: "Bahrain", flag: "BH", currency: "BHD" },
    { name: "Bangladesh", flag: "BD", currency: "BDT" },
    { name: "Barbados", flag: "BB", currency: "BBD" },
    { name: "Belarus", flag: "BY", currency: "BYN" },
    { name: "Belgium", flag: "BE", currency: "EUR" },
    { name: "Belize", flag: "BZ", currency: "BZD" },
    { name: "Benin", flag: "BJ", currency: "CDF" },
    { name: "Bhutan", flag: "BT", currency: "BTN" },
    { name: "Bolivia", flag: "BO", currency: "BOB" },
    { name: "Bosnia and Herzegovina", flag: "BA", currency: "BAM" },
    { name: "Botswana", flag: "BW", currency: "BWP" },
    { name: "Brazil", flag: "BR", currency: "BRL" },
    { name: "Brunei Darussalam", flag: "BN", currency: "BND" },
    { name: "Bulgaria", flag: "BG", currency: "BGN" },
    { name: "Burkina Faso", flag: "BF", currency: "BFA" },
    { name: "Burundi", flag: "BI", currency: "BIF" },
    { name: "Cabo Verde", flag: "CV", currency: "CVE" },
    { name: "Cambodia", flag: "KH", currency: "KHR" },
    { name: "Cameroon", flag: "CM", currency: "CDF" },
    { name: "Canada", flag: "CA", currency: "CAD" },
    { name: "Central African Republic", flag: "CF", currency: "CAF" },
    { name: "Chad", flag: "TD", currency: "CDF" },
    { name: "Chile", flag: "CL", currency: "CLP" },
    { name: "China", flag: "CN", currency: "CNY" },
    { name: "Colombia", flag: "CO", currency: "COP" },
    { name: "Comoros", flag: "KM", currency: "KMF" },
    { name: "Congo", flag: "CG", currency: "CDF" },
    { name: "Congo (Democratic Republic)", flag: "CD", currency: "CDF" },
    { name: "Costa Rica", flag: "CR", currency: "CRC" },
    { name: "Croatia", flag: "HR", currency: "HRK" },
    { name: "Cuba", flag: "CU", currency: "CUP" },
    { name: "Cyprus", flag: "CY", currency: "CYP" },
    { name: "Czech Republic", flag: "CZ", currency: "CZK" },
    { name: "Denmark", flag: "DK", currency: "DKK" },
    { name: "Djibouti", flag: "DJ", currency: "DJF" },
    { name: "Dominica", flag: "DM", currency: "DOP" },
    { name: "Dominican Republic", flag: "DO", currency: "DOP" },
    { name: "Ecuador", flag: "EC", currency: "USD" },
    { name: "Egypt", flag: "EG", currency: "EGP" },
    { name: "El Salvador", flag: "SV", currency: "SVC" },
    { name: "Equatorial Guinea", flag: "GQ", currency: "GNF" },
    { name: "Eritrea", flag: "ER", currency: "ERN" },
    { name: "Estonia", flag: "EE", currency: "EUR" },
    { name: "Eswatini", flag: "SZ", currency: "SZL" },
    { name: "Ethiopia", flag: "ET", currency: "ETB" },
    { name: "Fiji", flag: "FJ", currency: "FJD" },
    { name: "Finland", flag: "FI", currency: "EUR" },
    { name: "France", flag: "FR", currency: "EUR" },
    { name: "Gabon", flag: "GA", currency: "GAB" },
    { name: "Gambia", flag: "GM", currency: "GMD" },
    { name: "Georgia", flag: "GE", currency: "GEL" },
    { name: "Germany", flag: "DE", currency: "EUR" },
    { name: "Ghana", flag: "GH", currency: "GHS" },
    { name: "Greece", flag: "GR", currency: "EUR" },
    { name: "Grenada", flag: "GD", currency: "GRD" },
    { name: "Guatemala", flag: "GT", currency: "GTQ" },
    { name: "Guinea", flag: "GN", currency: "GNF" },
    { name: "Guinea-Bissau", flag: "GW", currency: "GNF" },
    { name: "Guyana", flag: "GY", currency: "GYD" },
    { name: "Haiti", flag: "HT", currency: "HTG" },
    { name: "Honduras", flag: "HN", currency: "HNL" },
    { name: "Hungary", flag: "HU", currency: "HUF" },
    { name: "Iceland", flag: "IS", currency: "ISK" },
    { name: "India", flag: "IN", currency: "INR" },
    { name: "Indonesia", flag: "ID", currency: "IDR" },
    { name: "Iran", flag: "IR", currency: "IRR" },
    { name: "Iraq", flag: "IQ", currency: "IQD" },
    { name: "Ireland", flag: "IE", currency: "EUR" },
    { name: "Israel", flag: "IL", currency: "ILS" },
    { name: "Italy", flag: "IT", currency: "EUR" },
    { name: "Jamaica", flag: "JM", currency: "JMD" },
    { name: "Japan", flag: "JP", currency: "JPY" },
    { name: "Jordan", flag: "JO", currency: "JOD" },
    { name: "Kazakhstan", flag: "KZ", currency: "KZT" },
    { name: "Kenya", flag: "KE", currency: "KES" },
    { name: "Kiribati", flag: "KI", currency: "KIR" },
    { name: "Korea (North)", flag: "KP", currency: "KPW" },
    { name: "Korea (South)", flag: "KR", currency: "KRW" },
    { name: "Kuwait", flag: "KW", currency: "KWD" },
    { name: "Kyrgyzstan", flag: "KG", currency: "KGS" },
    { name: "Laos", flag: "LA", currency: "LAK" },
    { name: "Latvia", flag: "LV", currency: "EUR" },
    { name: "Lebanon", flag: "LB", currency: "LBP" },
    { name: "Lesotho", flag: "LS", currency: "LSL" },
    { name: "Liberia", flag: "LR", currency: "LRD" },
    { name: "Libya", flag: "LY", currency: "LYD" },
    { name: "Liechtenstein", flag: "LI", currency: "CHF" },
    { name: "Lithuania", flag: "LT", currency: "EUR" },
    { name: "Luxembourg", flag: "LU", currency: "EUR" },
    { name: "Madagascar", flag: "MG", currency: "MGA" },
    { name: "Malawi", flag: "MW", currency: "MWK" },
    { name: "Malaysia", flag: "MY", currency: "MYR" },
    { name: "Maldives", flag: "MV", currency: "MVR" },
    { name: "Mali", flag: "ML", currency: "MRO" },
    { name: "Malta", flag: "MT", currency: "EUR" },
    { name: "Marshall Islands", flag: "MH", currency: "USD" },
    { name: "Mauritania", flag: "MR", currency: "MRU" },
    { name: "Mauritius", flag: "MU", currency: "MUR" },
    { name: "Mexico", flag: "MX", currency: "MXN" },
    { name: "Micronesia", flag: "FM", currency: "USD" },
    { name: "Moldova", flag: "MD", currency: "MDL" },
    { name: "Monaco", flag: "MC", currency: "EUR" },
    { name: "Mongolia", flag: "MN", currency: "MNT" },
    { name: "Montenegro", flag: "ME", currency: "EUR" },
    { name: "Morocco", flag: "MA", currency: "MAD" },
    { name: "Mozambique", flag: "MZ", currency: "MZN" },
    { name: "Myanmar", flag: "MM", currency: "MMK" },
    { name: "Namibia", flag: "NA", currency: "NAD" },
    { name: "Nauru", flag: "NR", currency: "AUD" },
    { name: "Nepal", flag: "NP", currency: "NPR" },
    { name: "Netherlands", flag: "NL", currency: "EUR" },
    { name: "New Zealand", flag: "NZ", currency: "NZD" },
    { name: "Nicaragua", flag: "NI", currency: "NIO" },
    { name: "Niger", flag: "NE", currency: "XOF" },
    { name: "Nigeria", flag: "NG", currency: "NGN" },
    { name: "North Macedonia", flag: "MK", currency: "MKD" },
    { name: "Norway", flag: "NO", currency: "NOK" },
    { name: "Oman", flag: "OM", currency: "OMR" },
    { name: "Pakistan", flag: "PK", currency: "PKR" },
    { name: "Palau", flag: "PW", currency: "USD" },
    { name: "Panama", flag: "PA", currency: "PAB" },
    { name: "Papua New Guinea", flag: "PG", currency: "PGK" },
    { name: "Paraguay", flag: "PY", currency: "PYG" },
    { name: "Peru", flag: "PE", currency: "PEN" },
    { name: "Philippines", flag: "PH", currency: "PHP" },
    { name: "Poland", flag: "PL", currency: "PLN" },
    { name: "Portugal", flag: "PT", currency: "EUR" },
    { name: "Qatar", flag: "QA", currency: "QAR" },
    { name: "Romania", flag: "RO", currency: "RON" },
    { name: "Russia", flag: "RU", currency: "RUB" },
    { name: "Rwanda", flag: "RW", currency: "RWF" },
    { name: "Saint Kitts and Nevis", flag: "KN", currency: "XCD" },
    { name: "Saint Lucia", flag: "LC", currency: "XCD" },
    { name: "Saint Vincent and the Grenadines", flag: "VC", currency: "XCD" },
    { name: "Samoa", flag: "WS", currency: "WST" },
    { name: "San Marino", flag: "SM", currency: "EUR" },
    { name: "Sao Tome and Principe", flag: "ST", currency: "STN" },
    { name: "Saudi Arabia", flag: "SA", currency: "SAR" },
    { name: "Senegal", flag: "SN", currency: "XOF" },
    { name: "Serbia", flag: "RS", currency: "RSD" },
    { name: "Seychelles", flag: "SC", currency: "SCR" },
    { name: "Sierra Leone", flag: "SL", currency: "SLL" },
    { name: "Singapore", flag: "SG", currency: "SGD" },
    { name: "Slovakia", flag: "SK", currency: "SKK" },
    { name: "Slovenia", flag: "SI", currency: "SIT" },
    { name: "Solomon Islands", flag: "SB", currency: "SBD" },
    { name: "Somalia", flag: "SO", currency: "SOS" },
    { name: "South Africa", flag: "ZA", currency: "ZAR" },
    { name: "South Sudan", flag: "SS", currency: "SSP" },
    { name: "Spain", flag: "ES", currency: "EUR" },
    { name: "Sri Lanka", flag: "LK", currency: "LKR" },
    { name: "Sudan", flag: "SD", currency: "SDG" },
    { name: "Suriname", flag: "SR", currency: "SRD" },
    { name: "Sweden", flag: "SE", currency: "SEK" },
    { name: "Switzerland", flag: "CH", currency: "CHF" },
    { name: "Syria", flag: "SY", currency: "SYP" },
    { name: "Taiwan", flag: "TW", currency: "TWD" },
    { name: "Tajikistan", flag: "TJ", currency: "TJS" },
    { name: "Tanzania", flag: "TZ", currency: "TZS" },
    { name: "Thailand", flag: "TH", currency: "THB" },
    { name: "Timor-Leste", flag: "TL", currency: "USD" },
    { name: "Togo", flag: "TG", currency: "XOF" },
    { name: "Tonga", flag: "TO", currency: "TOP" },
    { name: "Trinidad and Tobago", flag: "TT", currency: "TTD" },
    { name: "Tunisia", flag: "TN", currency: "TND" },
    { name: "Turkey", flag: "TR", currency: "TRY" },
    { name: "Turkmenistan", flag: "TM", currency: "TMT" },
    { name: "Tuvalu", flag: "TV", currency: "AUD" },
    { name: "Uganda", flag: "UG", currency: "UGX" },
    { name: "Ukraine", flag: "UA", currency: "UAH" },
    { name: "United Arab Emirates", flag: "AE", currency: "AED" },
    { name: "United Kingdom", flag: "GB", currency: "GBP" },
    { name: "United States", flag: "US", currency: "USD" },
    { name: "Uruguay", flag: "UY", currency: "UYU" },
    { name: "Uzbekistan", flag: "UZ", currency: "UZS" },
    { name: "Vanuatu", flag: "VU", currency: "VUV" },
    { name: "Vatican City", flag: "VA", currency: "EUR" },
    { name: "Venezuela", flag: "VE", currency: "VES" },
    { name: "Vietnam", flag: "VN", currency: "VND" },
    { name: "Yemen", flag: "YE", currency: "YER" },
    { name: "Zambia", flag: "ZM", currency: "ZMW" },
    { name: "Zimbabwe", flag: "ZW", currency: "ZWL" }
];
